export const RECEIVE_PORTFOLIO = 'RECEIVE_PORTFOLIO'
export const SEARCH_PORTFOLIO  = 'SEARCH_PORTFOLIO'
export const RECEIVE_TEAM      = 'RECEIVE_TEAM'
export const RECEIVE_LANGUAGES = 'RECEIVE_LANGUAGES'
